production:
  redis:
    url: redis://YOUR_REDIS_URL
  shell:
    buffer: 0.25
  reporter:
    http:
      # You get a Travis token on your application's profile page by signing in to your application via Github OAuth2.
      url: "YOUR_GITHUB_USERNAME:YOUR_TRAVIS_TOKEN@YOUR_APP.heroku.com"

development:
  redis:
    url: redis://localhost:6379
  shell:
    buffer: 0.25
  reporter:
    http:
      url: http://localhost:3000

test:
  redis:
    url: redis://localhost:6379
  shell:
    buffer: 0.25
  reporter:
    http:
      url: sven:123565790@localhost

